//! Shared skeleton for the portable slop-audit port. Every indicator module exposes
//! `pub fn analyze(repo: &Path) -> Indicator` and builds only on the helpers here, so
//! indicators are independent files that never touch each other or main.rs.
//!
//! The contract for a port: match the pre-registered Python reference
//! (l1_analyzer) exactly. The Python module and its tests are the frozen spec.

use std::collections::HashSet;
use std::path::{Component, Path, PathBuf};
use tree_sitter::Node;

pub mod indicators;
pub mod lang;

pub use lang::parser_for;

/// Must equal l1_analyzer.indicators._IGNORE_DIRS.
pub const IGNORE_DIRS: &[&str] = &[
    ".git", "node_modules", "venv", ".venv", "env", "__pycache__", ".pytest_cache",
    ".mypy_cache", ".ruff_cache", ".tox", ".eggs", "site-packages", "target", "build",
    "dist", "vendor",
];

/// One indicator result, mirroring l1_analyzer's L1Result shape for display and diffing.
#[derive(Debug, Clone)]
pub struct Indicator {
    pub code: String,
    pub label: String,
    pub value: String,
    pub band: String,
    pub details: String,
}

/// True when any path component is a vendored/tooling dir. Matches Python's
/// `set(path.parts) & _IGNORE_DIRS`.
pub fn in_ignored_dir(path: &Path) -> bool {
    let ignore: HashSet<&str> = IGNORE_DIRS.iter().copied().collect();
    path.components().any(|c| match c {
        Component::Normal(os) => os.to_str().map(|s| ignore.contains(s)).unwrap_or(false),
        _ => false,
    })
}

/// Python's `Path.is_file()` for one walk entry: a regular file, or a symlink that
/// resolves to one. Every scan in this crate filters on this, mirroring the reference's
/// `_rglob_files`. Two things it gets right that a bare `entry.file_type().is_file()`
/// does not: walkdir reports the *link's* own type, so a symlinked source file would be
/// dropped here and read there; and a directory whose name ends in a source extension
/// (node_modules/decimal.js is a real one) is excluded on both sides, so it is neither
/// measured nor counted as an unreadable file.
pub fn is_file_entry(entry: &walkdir::DirEntry) -> bool {
    let file_type = entry.file_type();
    if file_type.is_symlink() {
        entry.path().is_file()
    } else {
        file_type.is_file()
    }
}

/// Every FILE under `repo`, skipping nested checkouts. The single walk every indicator
/// uses, mirroring l1_analyzer.indicators._rglob_files.
///
/// A directory below the root that carries its own `.git` is a different repository with
/// its own history and its own audit: a submodule working copy, a vendored clone, or a
/// git worktree. Measuring it reports code that is not in this commit. The tool caught
/// this on itself: an agent's worktree held an older checkout of this repository, and the
/// gate charged eleven type escapes that existed only in that second copy.
///
/// `.git` is a directory in a clone and a FILE in a worktree, so the test is existence,
/// not is_dir. `filter_entry` prunes the whole subtree, so the walk never descends into a
/// nested checkout at all. `min_depth(1)` keeps the root's own `.git` from pruning
/// everything.
pub fn walk_repo(repo: &Path) -> impl Iterator<Item = walkdir::DirEntry> + '_ {
    walkdir::WalkDir::new(repo)
        .min_depth(1)
        .into_iter()
        .filter_entry(|entry| {
            !entry.file_type().is_dir() || !entry.path().join(".git").exists()
        })
        .filter_map(Result::ok)
        .filter(is_file_entry)
}

/// Every file under `repo` whose lowercased extension is in `exts` and not in an ignored
/// dir, read as text with invalid bytes replaced (mirrors read_text(errors="ignore")).
pub fn source_files(repo: &Path, exts: &[&str]) -> Vec<(PathBuf, String)> {
    let want: HashSet<&str> = exts.iter().copied().collect();
    let mut out = Vec::new();
    for entry in walk_repo(repo) {
        let path = entry.path();
        if in_ignored_dir(path) {
            continue;
        }
        let ext = match path.extension().and_then(|e| e.to_str()) {
            Some(e) => e.to_lowercase(),
            None => continue,
        };
        if !want.contains(ext.as_str()) {
            continue;
        }
        if let Ok(bytes) = std::fs::read(path) {
            out.push((path.to_path_buf(), String::from_utf8_lossy(&bytes).into_owned()));
        }
    }
    out
}

/// Conventional build/test/dev tooling recognised by filename, not by directory.
/// Must equal l1_analyzer.indicators._TOOLING_FILES.
pub const TOOLING_FILES: &[&str] = &["setup.py", "noxfile.py", "conftest.py", "tasks.py", "manage.py"];

/// _GENERATED_MARKERS: header sentinels that machine-generated source carries.
pub const GENERATED_MARKERS: &[&str] = &[
    "@generated",
    "Code generated by",
    "Generated by the protocol buffer compiler",
];

/// _repo_has_packages: any __init__.py outside a vendored/tooling dir. Tells a loose
/// dev/entry-point script from a flat script-only repo.
pub fn repo_has_packages(repo: &Path) -> bool {
    walk_repo(repo).any(|e| {
        e.path().file_name().and_then(|n| n.to_str()) == Some("__init__.py")
            && !in_ignored_dir(e.path())
    })
}

/// _is_generated: the file's header marks it machine-generated. Reads only the head,
/// so a hand-written file that mentions the phrase deep inside is unaffected; an
/// unreadable file is treated as not generated.
pub fn is_generated(path: &Path) -> bool {
    let bytes = match std::fs::read(path) {
        Ok(b) => b,
        Err(_) => return false,
    };
    let head = String::from_utf8_lossy(&bytes[..bytes.len().min(2048)]).into_owned();
    GENERATED_MARKERS.iter().any(|m| head.contains(m))
}

/// Must equal l1_analyzer.indicators._TEST_DIR_MARKERS. The two markers that name a test
/// directory. Everything else in an `extra` scope-out list is matched on the nose; these
/// two are also matched case-insensitively and as a dotted suffix, because C# names a test
/// project `<Project>.Tests` and an exact match never catches `Src/Newtonsoft.Json.Tests/`.
pub const TEST_DIR_MARKERS: &[&str] = &["test", "tests"];

/// Markers that corroborate a test directory by file content. Mirrors
/// _TEST_FRAMEWORK_MARKERS.
const TEST_FRAMEWORK_MARKERS: &[&str] = &[
    "import pytest", "import unittest", "from unittest", "@pytest",
    "org.junit", "org.testng", "using Xunit", "using NUnit",
    "Microsoft.VisualStudio.TestTools", "[TestMethod]", "[Fact]", "@Test",
    "\"testing\"", "#[test]", "#[cfg(test)]",
    "require 'rspec'", "require \"rspec\"", "minitest", "describe(",
    "from vitest", "require('mocha')",
];

/// The file-NAME half of the test-file conventions. Mirrors _test_file_by_name.
/// Excludes the path-component arm on purpose: using it would let a renamed directory
/// corroborate itself, which is the circularity this exists to break.
pub fn test_file_by_name(path: &Path) -> bool {
    let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("").to_lowercase();
    let stem = path.file_stem().and_then(|n| n.to_str()).unwrap_or("").to_lowercase();
    name.starts_with("test_") || name.starts_with("test-") || name.starts_with("test.")
        || stem.ends_with("_test") || stem.ends_with("-test") || stem.ends_with(".test")
        || stem.ends_with(".spec") || stem.ends_with("_spec") || stem.ends_with("-spec")
        || crate::indicators::git_ratios::TEST_STEM_SUFFIXES.iter().any(|sfx| {
            path.file_stem().and_then(|n| n.to_str()).map(|s| s.ends_with(sfx)).unwrap_or(false)
        })
}

/// True when a directory named like a test directory actually holds test code.
/// Mirrors _test_dir_corroborated.
///
/// A directory NAMED like a test directory is believed only if its contents corroborate
/// the claim. Without this, renaming a production package to `Core.Tests` removes it from
/// L1.15, L1.17 and L1.19 and flips the gate, with zero bytes of code changed. The
/// instrument's primary consumer is an AI, which optimises exactly what it is told to,
/// so a scope rule reading a free-to-forge name is an instruction to rename.
///
/// One-directional on purpose: a directory that fails to corroborate is MEASURED, never
/// dropped, so the rule cannot be turned into a cheaper score.
pub fn test_dir_corroborated(directory: &Path) -> bool {
    for entry in walkdir::WalkDir::new(directory).into_iter().filter_map(Result::ok) {
        if !is_file_entry(&entry) {
            continue;
        }
        if test_file_by_name(entry.path()) {
            return true;
        }
        if let Ok(bytes) = std::fs::read(entry.path()) {
            let head = String::from_utf8_lossy(&bytes[..bytes.len().min(4096)]).into_owned();
            if TEST_FRAMEWORK_MARKERS.iter().any(|m| head.contains(m)) {
                return true;
            }
        }
    }
    false
}

/// The ancestor directory of `path` whose own name is `component`. Mirrors _claiming_dir.
fn claiming_dir<'a>(path: &'a Path, component: &str) -> Option<&'a Path> {
    let mut current = path.parent();
    while let Some(dir) = current {
        if dir.file_name().and_then(|n| n.to_str()) == Some(component) {
            return Some(dir);
        }
        current = dir.parent();
    }
    None
}

/// _component_scoped_out: one path component is scoped out by `marker`. Exact for a
/// general marker; for a test marker, `Tests`, `tests`, `Foo.Tests` and `Foo.Test` count.
pub fn component_scoped_out(component: &str, marker: &str) -> bool {
    if component == marker {
        return true;
    }
    if !TEST_DIR_MARKERS.contains(&marker) {
        return false;
    }
    let lowered = component.to_lowercase();
    lowered == marker || lowered.ends_with(&format!(".{marker}"))
}

/// _extra_reason: the first `extra` marker any path component is scoped out by.
pub fn extra_reason(path: &Path, extra: &[&'static str]) -> Option<&'static str> {
    let parts: Vec<&str> = path
        .components()
        .filter_map(|c| match c {
            Component::Normal(os) => os.to_str(),
            _ => None,
        })
        .collect();
    for marker in extra {
        for component in &parts {
            if !component_scoped_out(component, marker) {
                continue;
            }
            // A TEST marker must also be corroborated by the claiming directory.
            if TEST_DIR_MARKERS.contains(marker) {
                if let Some(dir) = claiming_dir(path, component) {
                    if !test_dir_corroborated(dir) {
                        continue;
                    }
                }
            }
            return Some(marker);
        }
    }
    None
}

/// _bucket_reason: why this source file is scoped out of the audit, or None to keep
/// it. General and structural: it references no specific project. Disclosed, never
/// silent.
pub fn bucket_reason(
    path: &Path,
    repo: &Path,
    has_packages: bool,
    extra: &[&'static str],
) -> Option<&'static str> {
    let parts: HashSet<&str> = path
        .components()
        .filter_map(|c| match c {
            Component::Normal(os) => os.to_str(),
            _ => None,
        })
        .collect();
    if parts.iter().any(|p| IGNORE_DIRS.contains(p)) {
        return Some("vendored");
    }
    // The reason is the matched directory name itself, as in the reference.
    if let Some(reason) = extra_reason(path, extra) {
        return Some(reason);
    }
    if parts.contains("docs") {
        return Some("docs");
    }
    if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
        if TOOLING_FILES.contains(&name) {
            return Some("tooling");
        }
    }
    // A loose top-level source file sitting beside packages (the repo has packages and
    // its root is not itself one) is a dev/entry-point script, not the library. A flat,
    // script-only repo keeps its root scripts: they are the code.
    if has_packages && path.parent() == Some(repo) && !repo.join("__init__.py").exists() {
        return Some("root-script");
    }
    None
}

/// Length of `bytes.splitlines()` in Python: a line closes at each ASCII line
/// boundary (\n \r \r\n \v \f \x1c \x1d \x1e), with no trailing empty line after a
/// final boundary.
pub fn splitlines_len(bytes: &[u8]) -> usize {
    fn is_boundary(b: u8) -> bool {
        matches!(b, b'\n' | b'\r' | 0x0b | 0x0c | 0x1c | 0x1d | 0x1e)
    }
    let n = bytes.len();
    let mut i = 0;
    let mut count = 0;
    while i < n {
        while i < n && !is_boundary(bytes[i]) {
            i += 1;
        }
        count += 1;
        if i < n {
            if bytes[i] == b'\r' && i + 1 < n && bytes[i + 1] == b'\n' {
                i += 2;
            } else {
                i += 1;
            }
        }
    }
    count
}

/// `str.splitlines()` in Python: every line, split on the full Unicode boundary set a
/// decoded string carries. Beyond the ASCII boundaries `splitlines_len` handles, that
/// is NEL (U+0085), LINE SEPARATOR (U+2028) and PARAGRAPH SEPARATOR (U+2029).
///
/// Rust's own `str::lines()` splits on `\n` alone, so it disagrees with the reference
/// on any file carrying a lone `\r`, a form feed, or one of those three. Nothing in
/// this crate may count lines of file text with `str::lines()`; use this instead. The
/// difference is not hypothetical: it first showed up as a two-line drift in L1.8 and
/// a missed L1.16 hit.
pub fn py_splitlines(s: &str) -> Vec<&str> {
    fn is_boundary(c: char) -> bool {
        matches!(
            c,
            '\n' | '\r' | '\u{0b}' | '\u{0c}' | '\u{1c}' | '\u{1d}' | '\u{1e}'
                | '\u{85}' | '\u{2028}' | '\u{2029}'
        )
    }
    let mut lines = Vec::new();
    let mut start = 0usize;
    let mut iter = s.char_indices().peekable();
    while let Some((i, c)) = iter.next() {
        if !is_boundary(c) {
            continue;
        }
        lines.push(&s[start..i]);
        // \r\n closes one line, not two.
        if c == '\r' && iter.peek().map(|(_, next)| *next) == Some('\n') {
            iter.next();
            start = i + '\r'.len_utf8() + '\n'.len_utf8();
        } else {
            start = i + c.len_utf8();
        }
    }
    if start < s.len() {
        lines.push(&s[start..]);
    }
    lines
}

/// Length of `str.splitlines()`.
pub fn splitlines_count_str(s: &str) -> usize {
    py_splitlines(s).len()
}

/// `round(x, 2)` as the reference's JSON prints it: shortest round-trip, always with a
/// decimal point. Every ported percentage and density renders through this, so a value
/// diffs against the reference as text.
pub fn py_round2(x: f64) -> String {
    let rounded = (x * 100.0).round() / 100.0;
    let mut s = format!("{rounded}");
    if !s.contains('.') && !s.contains('e') {
        s.push_str(".0");
    }
    s
}

/// Count descendant nodes (inclusive) whose kind is `kind`.
pub fn count_kind(node: Node, kind: &str) -> usize {
    let mut n = usize::from(node.kind() == kind);
    let mut cursor = node.walk();
    for child in node.children(&mut cursor) {
        n += count_kind(child, kind);
    }
    n
}

/// Pure value-to-band map, identical to l1_analyzer.indicators.band.
pub fn band(value: f64, healthy: f64, slop: f64, higher_is_better: bool) -> &'static str {
    if higher_is_better {
        if value >= healthy { "Healthy" } else if value >= slop { "Not Healthy" } else { "Slop" }
    } else if value < healthy { "Healthy" } else if value < slop { "Not Healthy" } else { "Slop" }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    /// The boundary set Python's `str.splitlines()` uses, and the one Rust's
    /// `str::lines()` does not. Each case is the reference's answer, taken from
    /// CPython: `len("a\vb".splitlines()) == 2`, and so on for the rest.
    #[test]
    fn py_splitlines_matches_the_reference_boundaries() {
        let cases: &[(&str, usize)] = &[
            ("a\nb", 2),
            ("a\nb\n", 2),
            ("", 0),
            ("\n", 1),
            ("a\r\nb", 2),   // \r\n closes one line, not two
            ("a\rb", 2),     // lone \r: str::lines() would say 1
            ("a\u{0b}b", 2), // vertical tab
            ("a\u{0c}b", 2), // form feed
            ("a\u{1c}b", 2),
            ("a\u{1d}b", 2),
            ("a\u{1e}b", 2),
            ("a\u{85}b", 2),   // NEL
            ("a\u{2028}b", 2), // LINE SEPARATOR
            ("a\u{2029}b", 2), // PARAGRAPH SEPARATOR
            ("a\tb", 1),       // tab is not a boundary
        ];
        for (input, want) in cases {
            assert_eq!(
                py_splitlines(input).len(),
                *want,
                "py_splitlines({input:?})"
            );
        }
        assert_eq!(py_splitlines("a\r\nb\rc\u{2028}d"), vec!["a", "b", "c", "d"]);
    }

    /// C# convention is a project directory named `<Project>.Tests`, which an exact
    /// component match never catches, so every C# repository's test tree was measured as
    /// production code by L1.15, L1.17, L1.19 and the absolute-path check. A component is
    /// a test directory when, lowercased, it equals "tests"/"test" or ends ".tests"/".test".
    #[test]
    fn a_dotted_csharp_test_project_is_scoped_out() {
        let root = std::env::temp_dir().join(format!("slop-scope-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        // A real test project: its contents corroborate the name.
        fs::create_dir_all(root.join("Src/Newtonsoft.Json.Tests/Schema")).unwrap();
        fs::write(root.join("Src/Newtonsoft.Json.Tests/Schema/T.cs"), "using Xunit;\n[Fact] void A(){}\n").unwrap();
        // Production code, and two words that merely contain a marker.
        fs::create_dir_all(root.join("Src/Newtonsoft.Json")).unwrap();
        fs::write(root.join("Src/Newtonsoft.Json/Serializer.cs"), "class Serializer {}\n").unwrap();
        fs::create_dir_all(root.join("Src/Contests")).unwrap();
        fs::write(root.join("Src/Contests/Entry.cs"), "class Entry {}\n").unwrap();

        const EXTRA: &[&str] = &["tests", "test"];
        let scoped = |rel: &str| bucket_reason(&root.join(rel), &root, false, EXTRA);
        assert_eq!(scoped("Src/Newtonsoft.Json.Tests/Schema/T.cs"), Some("tests"));
        assert_eq!(scoped("Src/Newtonsoft.Json/Serializer.cs"), None);
        assert_eq!(scoped("Src/Contests/Entry.cs"), None);

        let _ = fs::remove_dir_all(&root);
    }

    /// The aperture-capture vector, closed. Renaming a production package to `Core.Tests`
    /// used to remove it from every source indicator and flip the gate, with zero bytes of
    /// code changed. A directory named like a test directory is now believed only if its
    /// contents corroborate the claim.
    #[test]
    fn a_renamed_production_directory_is_still_measured() {
        let root = std::env::temp_dir().join(format!("slop-rename-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(root.join("Core.Tests")).unwrap();
        fs::write(root.join("Core.Tests/app.py"), "from typing import Any\nCACHE = {}\n").unwrap();

        const EXTRA: &[&str] = &["tests", "test"];
        assert_eq!(bucket_reason(&root.join("Core.Tests/app.py"), &root, false, EXTRA), None);

        // The same directory, with one real test file in it, is believed.
        fs::write(root.join("Core.Tests/test_app.py"), "def test_x(): pass\n").unwrap();
        assert_eq!(bucket_reason(&root.join("Core.Tests/app.py"), &root, false, EXTRA), Some("tests"));

        let _ = fs::remove_dir_all(&root);
    }

    /// The bytes splitter agrees with the str splitter wherever both apply, so the two
    /// paths cannot drift apart on the ASCII boundaries they share.
    #[test]
    fn the_two_splitters_agree_on_ascii_boundaries() {
        for input in ["a\nb", "a\nb\n", "", "\n", "a\r\nb", "a\rb", "a\u{0c}b", "a\u{1e}b"] {
            assert_eq!(splitlines_len(input.as_bytes()), py_splitlines(input).len(), "{input:?}");
        }
    }
}

#[cfg(test)]
mod walk_tests {
    use super::walk_repo;
    use std::fs;

    /// A directory below the root carrying its own `.git` is a different repository.
    /// Measuring it reports code that is not in this commit. The tool caught this on
    /// itself: an agent worktree held an older checkout and the gate charged eleven type
    /// escapes that existed only there.
    #[test]
    fn a_nested_checkout_is_not_walked() {
        let root = std::env::temp_dir().join(format!("slop-walk-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(root.join(".git")).unwrap();
        fs::write(root.join("mine.py"), "x = 1\n").unwrap();

        // A vendored clone: .git is a directory.
        fs::create_dir_all(root.join("vendored-clone/.git")).unwrap();
        fs::write(root.join("vendored-clone/theirs.py"), "y = 2\n").unwrap();

        // A git worktree: .git is a FILE, which is the shape that produced the false
        // reading, so existence is the test rather than is_dir.
        fs::create_dir_all(root.join("agent-worktree/pkg")).unwrap();
        fs::write(root.join("agent-worktree/.git"), "gitdir: /elsewhere\n").unwrap();
        fs::write(root.join("agent-worktree/pkg/theirs.py"), "z = 3\n").unwrap();

        let names: Vec<String> = walk_repo(&root)
            .filter_map(|e| e.path().file_name()?.to_str().map(str::to_string))
            .filter(|n| n.ends_with(".py"))
            .collect();
        assert_eq!(names, vec!["mine.py".to_string()], "walked {names:?}");

        let _ = fs::remove_dir_all(&root);
    }
}
