//! Shared skeleton for the portable slop-audit port. Every indicator module exposes
//! `pub fn analyze(repo: &Path) -> Indicator` and builds only on the helpers here, so
//! indicators are independent files that never touch each other or main.rs.
//!
//! The contract for a port: match the pre-registered Python reference
//! (l1_analyzer) exactly. The Python module and its tests are the frozen spec.

use std::collections::HashSet;
use std::path::{Component, Path, PathBuf};
use tree_sitter::Node;

pub mod indicators;
pub mod lang;

pub use lang::parser_for;

/// Must equal l1_analyzer.indicators._IGNORE_DIRS.
pub const IGNORE_DIRS: &[&str] = &[
    ".git", "node_modules", "venv", ".venv", "env", "__pycache__", ".pytest_cache",
    ".mypy_cache", ".ruff_cache", ".tox", ".eggs", "site-packages", "target", "build",
    "dist", "vendor",
];

/// One indicator result, mirroring l1_analyzer's L1Result shape for display and diffing.
#[derive(Debug, Clone)]
pub struct Indicator {
    pub code: String,
    pub label: String,
    pub value: String,
    pub band: String,
    pub details: String,
}

/// True when any path component is a vendored/tooling dir. Matches Python's
/// `set(path.parts) & _IGNORE_DIRS`.
pub fn in_ignored_dir(path: &Path) -> bool {
    let ignore: HashSet<&str> = IGNORE_DIRS.iter().copied().collect();
    path.components().any(|c| match c {
        Component::Normal(os) => os.to_str().map(|s| ignore.contains(s)).unwrap_or(false),
        _ => false,
    })
}

/// Python's `Path.is_file()` for one walk entry: a regular file, or a symlink that
/// resolves to one. Every scan in this crate filters on this, mirroring the reference's
/// `_rglob_files`. Two things it gets right that a bare `entry.file_type().is_file()`
/// does not: walkdir reports the *link's* own type, so a symlinked source file would be
/// dropped here and read there; and a directory whose name ends in a source extension
/// (node_modules/decimal.js is a real one) is excluded on both sides, so it is neither
/// measured nor counted as an unreadable file.
pub fn is_file_entry(entry: &walkdir::DirEntry) -> bool {
    let file_type = entry.file_type();
    if file_type.is_symlink() {
        entry.path().is_file()
    } else {
        file_type.is_file()
    }
}

/// Every file under `repo` whose lowercased extension is in `exts` and not in an ignored
/// dir, read as text with invalid bytes replaced (mirrors read_text(errors="ignore")).
pub fn source_files(repo: &Path, exts: &[&str]) -> Vec<(PathBuf, String)> {
    let want: HashSet<&str> = exts.iter().copied().collect();
    let mut out = Vec::new();
    for entry in walkdir::WalkDir::new(repo).into_iter().filter_map(Result::ok) {
        let path = entry.path();
        if !is_file_entry(&entry) || in_ignored_dir(path) {
            continue;
        }
        let ext = match path.extension().and_then(|e| e.to_str()) {
            Some(e) => e.to_lowercase(),
            None => continue,
        };
        if !want.contains(ext.as_str()) {
            continue;
        }
        if let Ok(bytes) = std::fs::read(path) {
            out.push((path.to_path_buf(), String::from_utf8_lossy(&bytes).into_owned()));
        }
    }
    out
}

/// Conventional build/test/dev tooling recognised by filename, not by directory.
/// Must equal l1_analyzer.indicators._TOOLING_FILES.
pub const TOOLING_FILES: &[&str] = &["setup.py", "noxfile.py", "conftest.py", "tasks.py", "manage.py"];

/// _GENERATED_MARKERS: header sentinels that machine-generated source carries.
pub const GENERATED_MARKERS: &[&str] = &[
    "@generated",
    "Code generated by",
    "Generated by the protocol buffer compiler",
];

/// _repo_has_packages: any __init__.py outside a vendored/tooling dir. Tells a loose
/// dev/entry-point script from a flat script-only repo.
pub fn repo_has_packages(repo: &Path) -> bool {
    walkdir::WalkDir::new(repo)
        .into_iter()
        .filter_map(Result::ok)
        .any(|e| {
            is_file_entry(&e)
                && e.path().file_name().and_then(|n| n.to_str()) == Some("__init__.py")
                && !in_ignored_dir(e.path())
        })
}

/// _is_generated: the file's header marks it machine-generated. Reads only the head,
/// so a hand-written file that mentions the phrase deep inside is unaffected; an
/// unreadable file is treated as not generated.
pub fn is_generated(path: &Path) -> bool {
    let bytes = match std::fs::read(path) {
        Ok(b) => b,
        Err(_) => return false,
    };
    let head = String::from_utf8_lossy(&bytes[..bytes.len().min(2048)]).into_owned();
    GENERATED_MARKERS.iter().any(|m| head.contains(m))
}

/// _bucket_reason: why this source file is scoped out of the audit, or None to keep
/// it. General and structural: it references no specific project. Disclosed, never
/// silent.
pub fn bucket_reason(
    path: &Path,
    repo: &Path,
    has_packages: bool,
    extra: &[&'static str],
) -> Option<&'static str> {
    let parts: HashSet<&str> = path
        .components()
        .filter_map(|c| match c {
            Component::Normal(os) => os.to_str(),
            _ => None,
        })
        .collect();
    if parts.iter().any(|p| IGNORE_DIRS.contains(p)) {
        return Some("vendored");
    }
    // The reason is the matched directory name itself, as in the reference.
    for e in extra {
        if parts.contains(e) {
            return Some(e);
        }
    }
    if parts.contains("docs") {
        return Some("docs");
    }
    if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
        if TOOLING_FILES.contains(&name) {
            return Some("tooling");
        }
    }
    // A loose top-level source file sitting beside packages (the repo has packages and
    // its root is not itself one) is a dev/entry-point script, not the library. A flat,
    // script-only repo keeps its root scripts: they are the code.
    if has_packages && path.parent() == Some(repo) && !repo.join("__init__.py").exists() {
        return Some("root-script");
    }
    None
}

/// Length of `bytes.splitlines()` in Python: a line closes at each ASCII line
/// boundary (\n \r \r\n \v \f \x1c \x1d \x1e), with no trailing empty line after a
/// final boundary.
pub fn splitlines_len(bytes: &[u8]) -> usize {
    fn is_boundary(b: u8) -> bool {
        matches!(b, b'\n' | b'\r' | 0x0b | 0x0c | 0x1c | 0x1d | 0x1e)
    }
    let n = bytes.len();
    let mut i = 0;
    let mut count = 0;
    while i < n {
        while i < n && !is_boundary(bytes[i]) {
            i += 1;
        }
        count += 1;
        if i < n {
            if bytes[i] == b'\r' && i + 1 < n && bytes[i + 1] == b'\n' {
                i += 2;
            } else {
                i += 1;
            }
        }
    }
    count
}

/// `str.splitlines()` in Python: every line, split on the full Unicode boundary set a
/// decoded string carries. Beyond the ASCII boundaries `splitlines_len` handles, that
/// is NEL (U+0085), LINE SEPARATOR (U+2028) and PARAGRAPH SEPARATOR (U+2029).
///
/// Rust's own `str::lines()` splits on `\n` alone, so it disagrees with the reference
/// on any file carrying a lone `\r`, a form feed, or one of those three. Nothing in
/// this crate may count lines of file text with `str::lines()`; use this instead. The
/// difference is not hypothetical: it first showed up as a two-line drift in L1.8 and
/// a missed L1.16 hit.
pub fn py_splitlines(s: &str) -> Vec<&str> {
    fn is_boundary(c: char) -> bool {
        matches!(
            c,
            '\n' | '\r' | '\u{0b}' | '\u{0c}' | '\u{1c}' | '\u{1d}' | '\u{1e}'
                | '\u{85}' | '\u{2028}' | '\u{2029}'
        )
    }
    let mut lines = Vec::new();
    let mut start = 0usize;
    let mut iter = s.char_indices().peekable();
    while let Some((i, c)) = iter.next() {
        if !is_boundary(c) {
            continue;
        }
        lines.push(&s[start..i]);
        // \r\n closes one line, not two.
        if c == '\r' && iter.peek().map(|(_, next)| *next) == Some('\n') {
            iter.next();
            start = i + '\r'.len_utf8() + '\n'.len_utf8();
        } else {
            start = i + c.len_utf8();
        }
    }
    if start < s.len() {
        lines.push(&s[start..]);
    }
    lines
}

/// Length of `str.splitlines()`.
pub fn splitlines_count_str(s: &str) -> usize {
    py_splitlines(s).len()
}

/// `round(x, 2)` as the reference's JSON prints it: shortest round-trip, always with a
/// decimal point. Every ported percentage and density renders through this, so a value
/// diffs against the reference as text.
pub fn py_round2(x: f64) -> String {
    let rounded = (x * 100.0).round() / 100.0;
    let mut s = format!("{rounded}");
    if !s.contains('.') && !s.contains('e') {
        s.push_str(".0");
    }
    s
}

/// Count descendant nodes (inclusive) whose kind is `kind`.
pub fn count_kind(node: Node, kind: &str) -> usize {
    let mut n = usize::from(node.kind() == kind);
    let mut cursor = node.walk();
    for child in node.children(&mut cursor) {
        n += count_kind(child, kind);
    }
    n
}

/// Pure value-to-band map, identical to l1_analyzer.indicators.band.
pub fn band(value: f64, healthy: f64, slop: f64, higher_is_better: bool) -> &'static str {
    if higher_is_better {
        if value >= healthy { "Healthy" } else if value >= slop { "Not Healthy" } else { "Slop" }
    } else if value < healthy { "Healthy" } else if value < slop { "Not Healthy" } else { "Slop" }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The boundary set Python's `str.splitlines()` uses, and the one Rust's
    /// `str::lines()` does not. Each case is the reference's answer, taken from
    /// CPython: `len("a\vb".splitlines()) == 2`, and so on for the rest.
    #[test]
    fn py_splitlines_matches_the_reference_boundaries() {
        let cases: &[(&str, usize)] = &[
            ("a\nb", 2),
            ("a\nb\n", 2),
            ("", 0),
            ("\n", 1),
            ("a\r\nb", 2),   // \r\n closes one line, not two
            ("a\rb", 2),     // lone \r: str::lines() would say 1
            ("a\u{0b}b", 2), // vertical tab
            ("a\u{0c}b", 2), // form feed
            ("a\u{1c}b", 2),
            ("a\u{1d}b", 2),
            ("a\u{1e}b", 2),
            ("a\u{85}b", 2),   // NEL
            ("a\u{2028}b", 2), // LINE SEPARATOR
            ("a\u{2029}b", 2), // PARAGRAPH SEPARATOR
            ("a\tb", 1),       // tab is not a boundary
        ];
        for (input, want) in cases {
            assert_eq!(
                py_splitlines(input).len(),
                *want,
                "py_splitlines({input:?})"
            );
        }
        assert_eq!(py_splitlines("a\r\nb\rc\u{2028}d"), vec!["a", "b", "c", "d"]);
    }

    /// The bytes splitter agrees with the str splitter wherever both apply, so the two
    /// paths cannot drift apart on the ASCII boundaries they share.
    #[test]
    fn the_two_splitters_agree_on_ascii_boundaries() {
        for input in ["a\nb", "a\nb\n", "", "\n", "a\r\nb", "a\rb", "a\u{0c}b", "a\u{1e}b"] {
            assert_eq!(splitlines_len(input.as_bytes()), py_splitlines(input).len(), "{input:?}");
        }
    }
}
