"""A generated file is read as production source by every indicator but one.

`_is_generated` reads the machine-readable @generated convention that tree-sitter, protobuf
and several toolchains write into a header. The god-file count consults it, so a generated
file cannot make a repository look like a pile of hand-written logic. Nothing else does.

So a parser table, a protobuf module or a build stamp is graded for unreachable code, for
type escapes, for dead definitions and for Honest Code conformity, as though somebody sat
down and wrote it. It is not their code and the numbers are not about them.

Found by running the audit on this repository: the build hook writes a two-line stamp, the
marker went into its header to stop this, and the marker had no effect because scope never
asked. One reader consulted the convention and the scope everything else reads did not,
which is one fact with two owners and only one of them awake.
"""

import pathlib

import pytest
from l1_analyzer import scope

_MARKERS = ("# @generated by a tool. Do not edit.\n",
            "// Code generated by protoc. DO NOT EDIT.\n",
            "/* Generated by the protocol buffer compiler. */\n")


@pytest.mark.parametrize("header", _MARKERS)
def test_a_file_whose_header_says_it_is_generated_is_scoped_out(tmp_path, header):
    (tmp_path / "pkg").mkdir()
    (tmp_path / "pkg" / "__init__.py").write_text("")
    made = tmp_path / "pkg" / "table.py"
    made.write_text(header + "TABLE = {'a': 1}\n")
    assert scope._bucket_reason(made, tmp_path, True, scope.PRODUCTION) == "generated"


def test_a_hand_written_file_mentioning_the_phrase_deep_inside_is_kept(tmp_path):
    """The header window is the test, and it is why this is safe. A file discussing the
    convention in its own prose is not generated, and this repository has several."""
    (tmp_path / "pkg").mkdir()
    (tmp_path / "pkg" / "__init__.py").write_text("")
    written = tmp_path / "pkg" / "m.py"
    written.write_text("x = 1\n" * 400 + "# we honour the @generated convention here\n")
    assert scope._bucket_reason(written, tmp_path, True, scope.PRODUCTION) is None


def test_the_generated_file_is_not_read_as_production_source(tmp_path):
    (tmp_path / "pkg").mkdir()
    (tmp_path / "pkg" / "__init__.py").write_text("")
    (tmp_path / "pkg" / "made.py").write_text("# @generated\nMADE = 1\n")
    (tmp_path / "pkg" / "written.py").write_text("WRITTEN = 1\n")
    files, _ = scope._read_text_files(tmp_path, frozenset({".py"}), scope.PRODUCTION)
    names = {p.name for p, _ in files}
    assert "written.py" in names and "made.py" not in names, names


def test_the_god_file_count_reads_the_one_scope_rather_than_asking_again(tmp_path):
    """The god-file measure called `_is_generated` itself. Two readers of one convention is
    what let them drift, and only one of them was ever awake."""
    from l1_analyzer import indicators

    source = pathlib.Path(indicators.__file__).read_text()
    body = source.split("def _god_files")[1].split("\ndef ")[0]
    assert "_is_generated(" not in body, "the scope already decided this"


# ---------------------------------------------------------------------------
# The read and the decision, separated
#
# Reading the header is I/O and deciding what the header says is not. They were one
# function, which was tolerable while the only caller was itself a declared edge. Once
# the shared scope started calling it, the clause that puts I/O at the boundary caught
# it inside this package, on this package's own code. The split is that clause applied.
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("head", [
    "# @generated by a tool\nx = 1\n",
    "// Code generated by protoc. DO NOT EDIT.\n",
    "/* Generated by the protocol buffer compiler. */\n",
])
def test_a_marked_header_is_read_as_a_declaration(head):
    assert scope.head_carries_any(head, scope._GENERATED_MARKERS) is True


@pytest.mark.parametrize("head", ["", "x = 1\n", "# we honour the convention\n"])
def test_an_unmarked_header_is_not(head):
    assert scope.head_carries_any(head, scope._GENERATED_MARKERS) is False


def test_the_decision_needs_no_file_to_be_exercised():
    """The point of the split, and the reason the cases above are strings."""
    assert scope.head_carries_any("# @generated\n", scope._GENERATED_MARKERS)


def test_only_the_head_of_the_file_is_read(tmp_path):
    f = tmp_path / "big.py"
    f.write_text("x = 1\n" * 4000 + "# @generated\n")
    assert len(scope.boundary_in_file_head(f, 2048)) <= 2048
    assert scope.head_carries_any(scope.boundary_in_file_head(f, 2048), scope._GENERATED_MARKERS) is False


def test_an_unreadable_file_reports_an_empty_head_rather_than_a_verdict(tmp_path):
    """Which every caller reads as unmarked, so the file is audited rather than skipped.
    Guessing "generated" here would silently drop a file nobody could read."""
    f = tmp_path / "locked.py"
    f.write_text("# @generated\n")
    f.chmod(0o000)
    try:
        head = scope.boundary_in_file_head(f, 2048)
    finally:
        f.chmod(0o644)
    if head:
        pytest.skip("this filesystem let the unreadable file be read anyway")
    assert head == ""
