"""L1.17 god-file scope: production code only, with auditable disclosure.

The god-file smell is a human piling code into one file until every change touches
it and merge conflicts multiply. An append-only conformance table and a machine-
generated parser are neither, so both are scoped out through the same _bucket_reason
the finite-testability meter uses. What gets scoped out is disclosed (bucketed_large),
never dropped silently. Pure assertions on real files, no mocks.
"""

from l1_analyzer.indicators import _god_files
from l1_analyzer.scope import _is_generated

_BIG = "x = 1\n" * 1200            # >1000 lines
_SMALL = "y = 2\n" * 10
_GENERATED_C = "/* Automatically @generated by tree-sitter */\n" + ("int f() { return 0; }\n" * 1300)
_CONFORMANCE = "cases = [\n" + ("    ('a', 'b'),\n" * 1500) + "]\n"
# >1000 lines, but almost all of it is one dict literal: a table, not a logic pile.
_BIG_TABLE = "TABLE = {\n" + "".join(f'    "k{i}": {i},\n' for i in range(1200)) + "}\n"
# >1000 lines of actual logic: many small functions -> a real god-file.
_BIG_LOGIC = "".join(f"def f{i}(x):\n    return x + {i}\n\n\n" for i in range(400))


def _mkrepo(tmp_path, files):
    for rel, content in files.items():
        p = tmp_path / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content)
    return tmp_path


def test_conformance_and_generated_large_files_are_scoped_out_and_disclosed(tmp_path):
    repo = _mkrepo(tmp_path, {
        "pkg/__init__.py": "",
        "pkg/big_prod.py": _BIG,                              # a real production god-file
        "pkg/small.py": _SMALL,
        "pkg/honest-hd/src/parser.c": _GENERATED_C,           # machine-generated
        "conformance/laws_x.py": _CONFORMANCE,                # append-only conformance table
    })
    r = _god_files(repo)
    # exactly one production file exceeds 1k LOC: the real god-file, not the two scoped
    assert r["details"].startswith("1/")
    # both large non-production files are scoped out, each disclosed with its reason
    assert "1 >1k LOC scoped out (conformance)" in r["details"]
    assert "1 >1k LOC scoped out (generated)" in r["details"]


def test_a_genuine_production_god_file_is_still_flagged(tmp_path):
    repo = _mkrepo(tmp_path, {
        "pkg/__init__.py": "",
        "pkg/huge.py": _BIG,
    })
    r = _god_files(repo)
    assert r["value"] > 0                          # the metric still catches real god-files
    assert "scoped out" not in r["details"]        # nothing was scoped out here


def test_a_large_data_table_is_not_a_god_file(tmp_path):
    # >1000 total lines, but almost all one dict literal: a table is not the merge-
    # conflict smell (nobody hand-piles logic into a lookup table), so it is not counted.
    repo = _mkrepo(tmp_path, {"pkg/__init__.py": "", "pkg/table.py": _BIG_TABLE, "pkg/small.py": _SMALL})
    r = _god_files(repo)
    assert r["details"].startswith("0/")          # no production god-file
    assert r["value"] == 0.0


def test_a_large_logic_file_is_still_a_god_file(tmp_path):
    # >1000 lines of function bodies (not data) is exactly the smell L1.17 names.
    repo = _mkrepo(tmp_path, {"pkg/__init__.py": "", "pkg/logic.py": _BIG_LOGIC})
    r = _god_files(repo)
    assert r["value"] > 0
    assert r["details"].startswith("1/")


def test_is_generated_reads_only_the_header_sentinel(tmp_path):
    gen = tmp_path / "gen.c"
    gen.write_text("/* Automatically @generated by tree-sitter */\nint x;\n")
    handwritten = tmp_path / "hand.c"
    handwritten.write_text("int x;\n" * 500 + "// note: not @generated, just a comment far below\n")
    assert _is_generated(gen) is True
    assert _is_generated(handwritten) is False   # sentinel past the header window is ignored
