//! L1.17 god-file concentration: percentage of production files over 1000 CODE lines,
//! with large container literals (>= _MIN_TABLE_LINES) subtracted so a data table is
//! not read as a logic pile. Ported from l1_analyzer.indicators._god_files.
//!
//! PYTHON-ONLY PORT. The Python reference scans _GOD_FILE_EXTS (.py .rs .c .h .js .ts
//! .java .cs .go .rb); only the Python path is implemented here because only
//! tree-sitter-python is linked. On a Python repo the output is identical to the
//! reference. Other languages are follow-up: each needs its own grammar plus its
//! _LITERAL_NODES set for the code-line discount.

use crate::{band, in_ignored_dir, parser_for, Indicator};
use std::collections::{BTreeMap, HashSet};
use std::path::Path;
use tree_sitter::Node;

// _GOD_FILE_IGNORE = ("tests", "test", "conformance"); extra scope-out beyond vendored.
const GOD_FILE_IGNORE: &[&str] = &["tests", "test", "conformance"];

// _TOOLING_FILES: conventional build/test/dev tooling recognised by filename.
const TOOLING_FILES: &[&str] = &["setup.py", "noxfile.py", "conftest.py", "tasks.py", "manage.py"];

// _GENERATED_MARKERS: header sentinels that machine-generated source carries.
const GENERATED_MARKERS: &[&str] = &[
    "@generated",
    "Code generated by",
    "Generated by the protocol buffer compiler",
];

// _LITERAL_NODES["python"]: container-literal node types that read as a data table.
const PY_LITERAL_NODES: &[&str] = &["dictionary", "list", "set", "tuple"];

// _MIN_TABLE_LINES: a literal must span at least this many lines to count as a table.
const MIN_TABLE_LINES: usize = 12;

/// Length of `bytes.splitlines()` in Python: a line closes at each ASCII line boundary
/// (\n \r \r\n \v \f \x1c \x1d \x1e); no trailing empty line after a final boundary.
fn splitlines_len(bytes: &[u8]) -> usize {
    fn is_boundary(b: u8) -> bool {
        matches!(b, b'\n' | b'\r' | 0x0b | 0x0c | 0x1c | 0x1d | 0x1e)
    }
    let n = bytes.len();
    let mut i = 0;
    let mut count = 0;
    while i < n {
        while i < n && !is_boundary(bytes[i]) {
            i += 1;
        }
        count += 1;
        if i < n {
            if bytes[i] == b'\r' && i + 1 < n && bytes[i + 1] == b'\n' {
                i += 2;
            } else {
                i += 1;
            }
        }
    }
    count
}

/// str(round(pct, 2)) in Python: two decimals, then drop one trailing zero so an
/// integer-valued float reads "X.0" and a tenths-only value keeps one decimal.
fn py_value_str(pct: f64) -> String {
    let s = format!("{:.2}", pct);
    if s.ends_with('0') {
        s[..s.len() - 1].to_string()
    } else {
        s
    }
}

/// The set of path components, as Python's `set(path.parts)`.
fn parts(path: &Path) -> HashSet<&str> {
    path.components()
        .filter_map(|c| match c {
            std::path::Component::Normal(os) => os.to_str(),
            _ => None,
        })
        .collect()
}

/// _is_generated: only the 2 KiB header window is inspected for a sentinel.
fn is_generated(src: &[u8]) -> bool {
    let head = &src[..src.len().min(2048)];
    let text = String::from_utf8_lossy(head);
    GENERATED_MARKERS.iter().any(|m| text.contains(m))
}

/// _bucket_reason for the god-file scope (extra = _GOD_FILE_IGNORE). Why this source
/// file is scoped out of the audit, or None to keep it. Vendored, tests/test/
/// conformance, docs, tooling, and a loose root-script beside packages.
fn bucket_reason(path: &Path, repo: &Path, has_packages: bool) -> Option<&'static str> {
    if in_ignored_dir(path) {
        return Some("vendored");
    }
    let p = parts(path);
    for e in GOD_FILE_IGNORE {
        if p.contains(e) {
            return Some(e);
        }
    }
    if p.contains("docs") {
        return Some("docs");
    }
    let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
    if TOOLING_FILES.contains(&name) {
        return Some("tooling");
    }
    if has_packages && path.parent() == Some(repo) && !repo.join("__init__.py").exists() {
        return Some("root-script");
    }
    None
}

/// _god_file_reason: shared production scoping plus L1.17-specific generated exclusion.
fn god_file_reason(path: &Path, repo: &Path, has_packages: bool, src: &[u8]) -> Option<&'static str> {
    if let Some(r) = bucket_reason(path, repo, has_packages) {
        return Some(r);
    }
    let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
    if name.ends_with(".min.js") || name.ends_with(".min.css") || is_generated(src) {
        return Some("generated");
    }
    None
}

/// _data_literal_lines: lines spanned by large container literals under `node`. A
/// counted literal is not recursed into, so nested literals are counted once.
fn data_literal_lines(node: Node) -> usize {
    let span = node.end_position().row - node.start_position().row + 1;
    if PY_LITERAL_NODES.contains(&node.kind()) && span >= MIN_TABLE_LINES {
        return span;
    }
    let mut cursor = node.walk();
    let mut sum = 0;
    for child in node.children(&mut cursor) {
        sum += data_literal_lines(child);
    }
    sum
}

/// _code_line_count for a Python file: total lines minus large data-literal lines.
fn code_line_count(src: &[u8]) -> i64 {
    let total = splitlines_len(src) as i64;
    let mut parser = parser_for("python");
    match parser.parse(src, None) {
        Some(tree) => total - data_literal_lines(tree.root_node()) as i64,
        None => total,
    }
}

/// _repo_has_packages: any __init__.py outside a vendored/tooling dir.
fn repo_has_packages(py_files: &[std::path::PathBuf]) -> bool {
    py_files.iter().any(|f| {
        f.file_name().and_then(|n| n.to_str()) == Some("__init__.py") && !in_ignored_dir(f)
    })
}

/// _with_skipped: append an honest note when some files could not be read.
fn with_skipped(details: String, skipped: usize) -> String {
    if skipped == 0 {
        details
    } else {
        format!("{details}; {skipped} file(s) unreadable and excluded")
    }
}

pub fn analyze(repo: &Path) -> Indicator {
    // Collect every *.py path, including vendored/ignored dirs, so a large scoped-out
    // file can still be disclosed (mirrors Python's rglob, which sees ignored dirs).
    let mut py_files: Vec<std::path::PathBuf> = Vec::new();
    for entry in walkdir::WalkDir::new(repo).into_iter().filter_map(Result::ok) {
        if entry.file_type().is_file() {
            let path = entry.path();
            if path.file_name().and_then(|n| n.to_str()).map(|n| n.ends_with(".py")).unwrap_or(false) {
                py_files.push(path.to_path_buf());
            }
        }
    }
    let has_packages = repo_has_packages(&py_files);

    let mut prod_files = 0i64;
    let mut god_files = 0i64;
    let mut big_files = 0i64;
    let mut skipped = 0usize;
    let mut scoped: BTreeMap<&'static str, i64> = BTreeMap::new();

    for path in &py_files {
        let src = match std::fs::read(path) {
            Ok(b) => b,
            Err(_) => {
                skipped += 1;
                continue;
            }
        };
        if let Some(reason) = god_file_reason(path, repo, has_packages, &src) {
            if splitlines_len(&src) > 1000 {
                *scoped.entry(reason).or_insert(0) += 1;
            }
            continue;
        }
        let code = code_line_count(&src);
        prod_files += 1;
        if code > 1000 {
            god_files += 1;
        }
        if code > 4000 {
            big_files += 1;
        }
    }

    let god_pct = if prod_files > 0 {
        god_files as f64 / prod_files as f64 * 100.0
    } else {
        0.0
    };
    let band_value = if big_files > 0 {
        "Slop"
    } else {
        band(god_pct, 0.5, 2.0, false)
    };

    let mut note = format!("{god_files}/{prod_files} files >1k LOC, {big_files} >4k LOC");
    if !scoped.is_empty() {
        let joined: Vec<String> = scoped
            .iter()
            .map(|(r, n)| format!("{n} >1k LOC scoped out ({r})"))
            .collect();
        note.push_str("; ");
        note.push_str(&joined.join(", "));
    }

    Indicator {
        code: "L1.17".into(),
        label: "god-files".into(),
        value: py_value_str(god_pct),
        band: band_value.into(),
        details: with_skipped(note, skipped),
    }
}
